### PR TITLE
jei and rei integration

### PR DESCRIPTION
**Pull request by malezjaa**

### CODE REVIEW

**Review by Gcat101 — CHANGES_REQUESTED** [review]
`REIEvents.hide("item")` and `REIEvents.add("item")` wouldn’t work, you need to put them inside of a function like I did with tag and registry events

**Review by Gcat101 — COMMENTED** [review]
Also you don’t need to add brackets when you only have one argument for a function, like you can use `callback => {` and not `(callback) => {`

**Comment by Gcat101** [comment]
Also tabs are 4 spaces imo, but that’s just a formatting thing so idc

**Comment by malezjaa** [comment]
i fixed it, and brackets thing are also from fromatter

**Review by Gcat101 — APPROVED** [review]

**Comment by Gcat101** [comment]
Sure I’ll reformat it later

**Pull request merged**
